#test:
#  prop: testValue
server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
      username: root
      password: root

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

testcase:
  book:
    id: ${random.int}
    scopeId1: ${random.int(10)}
    scopeId2: ${random.int(5,10)}
    name: ${random.value}
    name2: 聂傲杰${random.value}
    uuid: ${random.uuid}
    publishTime: ${random.long}