#应用环境，公共配置
spring:
  profiles:
    active: pro
---
#设置环境
#生产环境

#下面这种写法已经过时
#spring:
#  profiles: dev
#下面这种写法是最新的
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 80
---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 81
---
#测试环境
spring:
  config:
    activate:
      on-profile: test
server:
  port: 82
