server:
  port: 80

spring:
#  如果不使用activemq的话可以先注释掉，或者把activemq的服务启动。
#  activemq:
#    broker-url: tcp://localhost:61616
#  jms:
#    template:
#      # 配置一个默认的保存位置
#      default-destination: test
#    # 发布订阅的形式，默认是点对点
#    pub-sub-domain: true

  rabbitmq:
    host: localhost
    port: 5672

rocketmq:
  name-server: localhost:9876
  producer:
    group: group_rocketmq