server:
  port: 80

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  main:
    allow-circular-references: true


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto

jetcache:
  areaInCacheName: false  #（默认true）true的cacheName:default_book::1；false的cacheName:book::1
  statIntervalMinutes: 1
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson


  remote:
    default:
      keyConvertor: fastjson #使用方法注解时，必须指定key序列化方式，否则会报空指针异常
      valueEncode: java #序列化的时候，转化为一个Java对象
      valueDecode: java #反序列化的时候，也需要转化为一个Java对象
      type: redis
      host: localhost
      port: 6379
      poolConfig:
        maxTotal: 50
    sms:
      type: redis
      host: localhost
      port: 6379
      poolConfig:
        maxTotal: 50